apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secret-rolebinding
subjects:
- kind: ServiceAccount
  name: kubectl
roleRef:
  kind: Role
  name: create-secret-role
  apiGroup: rbac.authorization.k8s.io